---
- name: Install OracleDB | Extract files
  unarchive:
      src={{ oracle_stage }}/{{ item[0].filename }}
      dest={{ oracle_home_path }}
      copy=no
      creates="{{ oracle_home_path }}/{{ item[0].creates}}"
  with_nested:
    - "{{oracle_sw_image_db}}"
    - "{{db_homes_installed}}"
  become_user: "{{ oracle_user }}"
  run_once: "{{ configure_cluster}}"
  when: item[0].version == db_homes_config[item[1].home]['version'] and item[1].state|lower == 'present' and oracle_sw_copy and oracle_home_path not in existing_dbhome.stdout_lines
  tags:
    - oradbswunpack

- name: Install OracleDB | Extract files (from remote location)
  unarchive:
      src={{ oracle_stage_remote }}/{{ item[0].filename }}
      dest={{ oracle_home_path }}
      copy=no
      creates="{{ oracle_home_path }}/{{ item[0].creates}}"
  with_nested:
    - "{{oracle_sw_image_db}}"
    - "{{db_homes_installed}}"
  become_user: "{{ oracle_user }}"
  run_once: "{{ configure_cluster}}"
  when: item[0].version == db_homes_config[item[1].home]['version'] and item[1].state|lower == 'present'  and not oracle_sw_copy and oracle_home_path not in existing_dbhome.stdout_lines
  tags:
    - oradbswunpack

#fix for 19c at Oracle 8
- name: Install OracleDB | CV_ASSUME_DISTID issue fix
  shell: "export CV_ASSUME_DISTID=OEL8.1"
  become_user: "{{ oracle_user }}"

- name: Install OracleDB | CV_ASSUME_DISTID issue fix
  shell: "echo 'CV_ASSUME_DISTID=OEL8.1' >> {{ oracle_home_path }}/cv/admin/cvu_config"
  become_user: "{{ oracle_user }}"

- name: Install OracleDB | Install Oracle Database Server
  shell: "{{ oracle_home_path }}/runInstaller -responseFile {{ oracle_rsp_stage }}/{{ oracle_db_responsefile }} -ignorePrereq -silent -waitforcompletion"
  become_user: "{{ oracle_user }}"
  run_once: "{{ configure_cluster}}"
  when: oracle_home_path not in existing_dbhome.stdout_lines
  tags:
    - oradbinstall
  register: oradbinstall
  #failed_when: oradbinstall.rc not in [0,6]

- name: Install OracleDB | Get Install Logs
  find:
    paths: "{{ oracle_inventory_loc }}/logs/"
    patterns: "installActions*.log"
  register: log_files

- debug: var=oradbinstall.stdout_lines
  run_once: "{{ configure_cluster }}"
  when: oracle_home_path not in existing_dbhome.stdout_lines and oradbinstall.changed
  tags:
   - oradbinstall
  ignore_errors: true