 - sts_assume_role:
     role_arn: "{{rolearn}}"
     role_session_name: "{{rolename}}"
   register: assumed_role

 - set_fact:
     new_ec2: "{{item}}"
   with_lines: cat ./instance_ip_address1

 - debug:
     var: new_ec2

 - add_host:
     hostname: "{{new_ec2}}"
     ansible_user: ec2-user
     ansible_ssh_private_key_file: .ssh/<<keyname>>


 - name: Wait for Box To Be Available
   wait_for_connection:
   delegate_to: "{{new_ec2}}"

 - include: public.yml
