---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CF for implementing Guard Duty'


Resources:
  resdetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: "TWENTY_MINUTES"
