---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CF for creating the ScoutSuite Bucket

Resources:
  ScoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'scoutrunner-${AWS::AccountId}-${AWS::Region}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      Tags:
        -
          Key: TechnicalOwner
          Value: David Adams
  ScoutBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'ScoutBucket'
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: s3:GetObject
            Resource: !Sub '${ScoutBucket.Arn}/*'
            Condition:
              IpAddress:
                aws:SourceIp:
                  - 192.168.188.226
                  - 10.0.232.81
                  - 172.0.140.103
                  - 10.110.101.92

Outputs:
  BucketName:
    Value: !Ref 'ScoutBucket'
